# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kraken.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0ckraken.proto\x12\x06kraken\"G\n\x14KrakenMessageRequest\x12\x0c\n\x04kind\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x0f\n\x07payload\x18\x03 \x01(\t\"\'\n\x15KrakenMessageResponse\x12\x0e\n\x06status\x18\x01 \x01(\x05\x32V\n\rKrakenMessage\x12\x45\n\x04Send\x12\x1c.kraken.KrakenMessageRequest\x1a\x1d.kraken.KrakenMessageResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'kraken_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_KRAKENMESSAGEREQUEST']._serialized_start=24
  _globals['_KRAKENMESSAGEREQUEST']._serialized_end=95
  _globals['_KRAKENMESSAGERESPONSE']._serialized_start=97
  _globals['_KRAKENMESSAGERESPONSE']._serialized_end=136
  _globals['_KRAKENMESSAGE']._serialized_start=138
  _globals['_KRAKENMESSAGE']._serialized_end=224
# @@protoc_insertion_point(module_scope)
